spring:
  profiles:
#    active: dev-docker
    active: dev

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

forum:
  jwt:
    expiration: 3600000
    secret: VCTmtvHoR6x7knqi_5hrChk9Zlit-w8wpxL8O3kbgeU
---

spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-admin

---

spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum-test
    username: sa
    password:
    initialization-mode: never

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-admin

---

spring:
  profiles: dev-docker
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forum
    username: dbuser
    password: pass123


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

---

spring:
  profiles: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${FORUM_DATABASE_URL}
    username: ${FORUM_DATABASE_USERNAME}
    password: ${FORUM_DATABASE_PASSWORD}

forum:
  jwt:
    secret: ${FORUM_JWT_SECRET}
